[package]
name = "iio"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sorter = {path = "../sorter"}
clap = "4.0.25"
industrial-io = "0.5.1"
